- name: Ensure Shepherd stack is configured
  community.docker.docker_stack:
    state: present
    name: shepherd
    compose:
      - services:
          shepherd:
            image: containrrr/shepherd
            environment:
              # Beware YAML gotchas regarding quoting:
              # With KEY: 'VALUE', quotes are part of yaml syntax and thus get stripped
              # but with KEY='VALUE', they are part of the value and stay there,
              # causing problems!
              TZ: 'Australia/Melbourne'
              SLEEP_TIME: '1m'
              FILTER_SERVICES: 'label=shepherd.enable=true'
              VERBOSE: 'true'
              #UPDATE_OPTIONS: '--update-delay=30s'
              #ROLLBACK_OPTIONS: '--rollback-delay=0s'
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
            deploy:
              placement:
                constraints:
                  - node.role == manager
